substitutions:
  name: dps-tx
  external_components_source: github://syssi/esphome-dps@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
logger:
  level: DEBUG

uart:
  id: uart0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  debug:
    direction: TX

modbus:
  id: modbus0
  uart_id: uart0
  send_wait_time: 0ms

dps:
  id: dps0
  modbus_id: modbus0
  update_interval: 5s

binary_sensor:
  - platform: dps
    output:
      name: "${name} output"
    key_lock:
      name: "${name} key lock"
    constant_current_mode:
      name: "${name} constant current mode"

sensor:
  - platform: dps
    output_voltage:
      name: "${name} output voltage"
    output_current:
      name: "${name} output current"
    output_power:
      name: "${name} output power"
    input_voltage:
      name: "${name} input voltage"
    voltage_setting:
      name: "${name} voltage setting"
    current_setting:
      name: "${name} current setting"
    backlight_brightness:
      name: "${name} backlight brightness"
    firmware_version:
      name: "${name} firmware version"

text_sensor:
  - platform: dps
    protection_status:
      name: "${name} protection status"
    device_model:
      name: "${name} device model"

switch:
  - platform: dps
    output:
      name: "${name} output"
    key_lock:
      name: "${name} key lock"

number:
  - platform: dps
    voltage_setting:
      name: "${name} voltage setting"
    current_setting:
      name: "${name} current setting"
