substitutions:
  name: dps
  device_description: "Monitor and control a RDTech Digital Control Power Supply (DPS) via UART-TTL"
  external_components_source: github://syssi/esphome-dps@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-dps"
    version: 1.0.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

uart:
  id: uart_0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

modbus:
  id: modbus0
  uart_id: uart_0
  send_wait_time: 0ms

dps:
  id: dps0
  modbus_id: modbus0
  update_interval: 5s

binary_sensor:
  - platform: dps
    output:
      name: "${name} output"
    key_lock:
      name: "${name} key lock"
    constant_current_mode:
      name: "${name} constant current mode"

sensor:
  - platform: dps
    output_voltage:
      name: "${name} output voltage"
    output_current:
      name: "${name} output current"
    output_power:
      name: "${name} output power"
    input_voltage:
      name: "${name} input voltage"
    voltage_setting:
      name: "${name} voltage setting"
    current_setting:
      name: "${name} current setting"
    backlight_brightness:
      name: "${name} backlight brightness"
    firmware_version:
      name: "${name} firmware version"

text_sensor:
  - platform: dps
    protection_status:
      name: "${name} protection status"
    device_model:
      name: "${name} device model"

switch:
  - platform: dps
    output:
      name: "${name} output"
    key_lock:
      name: "${name} key lock"

number:
  - platform: dps
    voltage_setting:
      name: "${name} voltage setting"
    current_setting:
      name: "${name} current setting"
